### ISSUE TITLE
Can teach how to deploy to Google Cloud

### ISSUE THREAD

**Issue by TommyYehCool** [manish-in-java/spring-boot-rest#1]
I try the same build.gradle as your.

When I try "gradle appengineDeploy".

Got error
Task 'appengineDeploy' not found in root project

Do you know the right command can share to me ?

**Comment by manish-in-java** [comment]
The Gradle build file does not include the Google App Engine plugin. Please see the instructions for adding and using the plugin in the [official documentation](https://cloud.google.com/appengine/docs/flexible/java/using-gradle).
